// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeLink_TCC.Config;

#nullable disable

namespace SafeLink_TCC.Migrations
{
    [DbContext(typeof(DbConfig))]
    [Migration("20250925224851_Banco-Atualizado")]
    partial class BancoAtualizado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SafeLink_TCC.Models.AlunoMODEL", b =>
                {
                    b.Property<int>("Id_Aluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Aluno"));

                    b.Property<string>("Email_Aluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Aluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha_Aluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Aluno");

                    b.HasIndex("Id_Nivel");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.AnexoDenunciaMODEL", b =>
                {
                    b.Property<int>("Id_Anexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Anexo"));

                    b.Property<string>("Caminho_anexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Arquivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Anexo");

                    b.ToTable("AnexosDenuncia");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.CargoMODEL", b =>
                {
                    b.Property<int>("Id_cargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_cargo"));

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("nome_cargo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_cargo");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.CidadeMODEL", b =>
                {
                    b.Property<int>("Id_cidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_cidade"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome_cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_cidade");

                    b.HasIndex("EstadoId");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.DenunciaAnexoMODEL", b =>
                {
                    b.Property<int>("Id_anexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_anexo"));

                    b.Property<int>("AnexoId")
                        .HasColumnType("int");

                    b.Property<int>("DenunciaId")
                        .HasColumnType("int");

                    b.HasKey("Id_anexo");

                    b.HasIndex("AnexoId");

                    b.HasIndex("DenunciaId");

                    b.ToTable("Denuncia_Anexo");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.DenunciaMODEL", b =>
                {
                    b.Property<int>("Id_denuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_denuncia"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("EscolaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataCriacao_denuncia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricao_denuncia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("status_denuncia")
                        .HasColumnType("int");

                    b.Property<string>("titulo_denuncia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_denuncia");

                    b.HasIndex("AlunoId");

                    b.HasIndex("EscolaId");

                    b.ToTable("Denuncia");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.Denuncia_TestemunhaMODEL", b =>
                {
                    b.Property<int>("Id_Denuncia_testemunha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Denuncia_testemunha"));

                    b.Property<int>("DenunciaId")
                        .HasColumnType("int");

                    b.Property<int>("TestemunhaId")
                        .HasColumnType("int");

                    b.HasKey("Id_Denuncia_testemunha");

                    b.HasIndex("DenunciaId");

                    b.HasIndex("TestemunhaId");

                    b.ToTable("Denuncia_Testemunha");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.EscolaMODEL", b =>
                {
                    b.Property<int>("Id_escola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_escola"));

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<string>("cnpj_escola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("endereco_escola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome_escola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefone_escola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_escola");

                    b.HasIndex("CidadeId");

                    b.ToTable("Escola");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.EstadoMODEL", b =>
                {
                    b.Property<int>("Id_Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Estado"));

                    b.Property<string>("Nome_Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sigla_Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Estado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.FuncionarioMODEL", b =>
                {
                    b.Property<int>("Id_Funcionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Funcionario"));

                    b.Property<string>("Cargo_Funcionario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Departamento_Funcionario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome_Funcionario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Funcionario");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.NivelMODEL", b =>
                {
                    b.Property<int>("Id_Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Nivel"));

                    b.Property<string>("Nome_Nivel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Nivel");

                    b.ToTable("Niveis");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.Testemunha_DenunciaMODEL", b =>
                {
                    b.Property<int>("Id_Testemunha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Testemunha"));

                    b.Property<string>("Nome_Testemunha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone_Testemunha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Testemunha");

                    b.ToTable("TestemunhasDenuncia");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.UsuarioMODEL", b =>
                {
                    b.Property<int>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_usuario"));

                    b.Property<string>("Email_usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NivelId")
                        .HasColumnType("int");

                    b.Property<string>("Nome_usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha_usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_usuario");

                    b.HasIndex("NivelId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.AlunoMODEL", b =>
                {
                    b.HasOne("SafeLink_TCC.Models.NivelMODEL", "Nivel")
                        .WithMany()
                        .HasForeignKey("Id_Nivel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.CargoMODEL", b =>
                {
                    b.HasOne("SafeLink_TCC.Models.FuncionarioMODEL", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.CidadeMODEL", b =>
                {
                    b.HasOne("SafeLink_TCC.Models.EstadoMODEL", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.DenunciaAnexoMODEL", b =>
                {
                    b.HasOne("SafeLink_TCC.Models.AnexoDenunciaMODEL", "Anexo")
                        .WithMany()
                        .HasForeignKey("AnexoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeLink_TCC.Models.DenunciaMODEL", "Denuncia")
                        .WithMany()
                        .HasForeignKey("DenunciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anexo");

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.DenunciaMODEL", b =>
                {
                    b.HasOne("SafeLink_TCC.Models.AlunoMODEL", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeLink_TCC.Models.EscolaMODEL", "Escola")
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Escola");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.Denuncia_TestemunhaMODEL", b =>
                {
                    b.HasOne("SafeLink_TCC.Models.DenunciaMODEL", "Denuncia")
                        .WithMany()
                        .HasForeignKey("DenunciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeLink_TCC.Models.Testemunha_DenunciaMODEL", "Testemunha")
                        .WithMany()
                        .HasForeignKey("TestemunhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncia");

                    b.Navigation("Testemunha");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.EscolaMODEL", b =>
                {
                    b.HasOne("SafeLink_TCC.Models.CidadeMODEL", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.UsuarioMODEL", b =>
                {
                    b.HasOne("SafeLink_TCC.Models.NivelMODEL", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });
#pragma warning restore 612, 618
        }
    }
}
