// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeLink_TCC.Config;

#nullable disable

namespace SafeLink_TCC.Migrations
{
    [DbContext(typeof(DbConfig))]
    partial class DbConfigModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SafeLink_TCC.Models.AlunoMODEL", b =>
                {
                    b.Property<int>("Id_Aluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Aluno"));

                    b.Property<string>("Email_Aluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NivelId")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Aluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha_Aluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Aluno");

                    b.HasIndex("NivelId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.AnexoDenunciaMODEL", b =>
                {
                    b.Property<int>("Id_Anexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Anexo"));

                    b.Property<string>("Caminho_anexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Arquivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Anexo");

                    b.ToTable("AnexosDenuncia");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.EstadoMODEL", b =>
                {
                    b.Property<int>("Id_Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Estado"));

                    b.Property<string>("Nome_Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sigla_Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Estado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.FuncionarioMODEL", b =>
                {
                    b.Property<int>("Id_Funcionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Funcionario"));

                    b.Property<string>("Cargo_Funcionario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Departamento_Funcionario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome_Funcionario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Funcionario");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.NivelMODEL", b =>
                {
                    b.Property<int>("Id_Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Nivel"));

                    b.Property<string>("Nome_Nivel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Nivel");

                    b.ToTable("Niveis");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.Testemunha_DenunciaMODEL", b =>
                {
                    b.Property<int>("Id_Testemunha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Testemunha"));

                    b.Property<string>("Nome_Testemunha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone_Testemunha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Testemunha");

                    b.ToTable("TestemunhasDenuncia");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.UsuarioMODEL", b =>
                {
                    b.Property<int>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_usuario"));

                    b.Property<string>("Email_usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NivelId")
                        .HasColumnType("int");

                    b.Property<string>("Nome_usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha_usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_usuario");

                    b.HasIndex("NivelId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.AlunoMODEL", b =>
                {
                    b.HasOne("SafeLink_TCC.Models.NivelMODEL", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("SafeLink_TCC.Models.UsuarioMODEL", b =>
                {
                    b.HasOne("SafeLink_TCC.Models.NivelMODEL", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });
#pragma warning restore 612, 618
        }
    }
}
